name: Update Homebrew Formula

on:
  push:
    tags: "v*"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes to the repo
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-path: Formula/commit-lsp.rb
          homebrew-tap: texel-sensei/commit-lsp
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
